{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "balenthiranhelm.fullname" . }}
  labels:
    {{- include "balenthiranhelm.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className | default "nginx" }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          {{- range $.Values.apps }}
          {{- if .ingress }}
          - path: {{ .ingress.path }}
            pathType: {{ .ingress.pathType | default "Prefix" }}
            backend:
              service:
                name: {{ include "balenthiranhelm.fullname" $ }}-{{ .name }}
                port:
                  number: {{ .service.port }}
          {{- end }}
          {{- end }}
    {{- end }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
